version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.23
    steps:
      - checkout
      - run:
          name: install hdf5
          command: sudo apt-get install pkg-config libhdf5-dev
      - run:
          name: setup environment
          command: |
            mkdir ~/env
            virtualenv ~/env
            source ~/env/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - run:
          name: running tests
          command: |
            mkdir ~/test_reports
            source ~/env/bin/activate
            python setup.py build_ext --inplace
            pytest --junitxml=~/test_reports/pytest-results.xml tests/test_dna_to_peptide.py tests/test_filter.py tests/test_utils.py tests/test_mutations.py
      - store_test_results:
          path: ~/test_reports
