version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: install hdf5
          command: sudo apt-get install pkg-config libhdf5-103 libhdf5-dev
      - run:
          name: install R
          command: sudo apt install r-base
      - run:
          name: setup environment
          command: |
            mkdir ~/env
            virtualenv ~/env
            source ~/env/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - run:
          name: running tests
          command: |
            mkdir ~/test_reports
            source ~/env/bin/activate
            # pytest --junitxml=~/test_reports/pytest-results.xml
      - store_test_results:
          path: ~/test_reports
